config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "data" => 'farm_blocks#get_iot_shadows'
  post "data" => 'farm_blocks#get_iot_shadows'

  get "water_tanks/:water_tank_id/data" => 'water_tanks#get_tank_data'
  get "about" => 'welcome#about', :as => "about"
  get "new" => 'devices#new', :as => "new"
  post "new" => 'devices#login'

  get "ok" => 'devices#ok', :as => "ok"

  get "pricing" => "welcome#pricing", :as => "pricing"
  get "blog" => "welcome#blog", :as => "blog"
  get "contact" => "welcome#contact", :as => "contact"
  get "landing" => "welcome#landing", :as => "landing"
  get "users/:user_id/farm_blocks" => "farm_blocks#index", :as => "dashboard"

  post "alert/seen" => "alerts#user_check_alert"
  get "get_all_alerts" => "alerts#get_all_alerts"
  get "farm_block_water_tank" => "farm_blocks#show"

  resources :users, only: [:new, :create, :edit, :update, :show], shallow: true  do

    member do
      get :confirm_email
    end

    resources :farm_blocks, shallow: true do
      resources :addresses
      resources :locations

      resources :water_tanks, shallow: true  do
        resources :locations
        resources :alerts
      end

      resources :inflow_meters do
        resources :locations
        resources :alerts
      end
    end
  end

  resources :sessions, only: [:create, :destroy]
  get "login" => 'sessions#new', :as => "login"
  get "users" => 'users#new'
  get "logout" => 'sessions#destroy', :as => "logout"

  resources :charges

end

app/models/inflow_meter.rb
class InflowMeter < ActiveRecord::Base
  belongs_to :farm_block
  has_one :location, as: :locationable
  has_many :alerts, as: :alertable

  def alert_attributes
    [
      ["Output", 1]
    ]
  end

  def get_inflow_data
    return rand(30..100)
  end

  validates_presence_of :calibration_unit
end

app/controllers/inflow_meters_controller.rb
class InflowMetersController < ApplicationController

  # require "Sensor"
  require "losant_rest"

  def new
    @farm_block = FarmBlock.find_by(id: params[:farm_block_id])
    @inflow_meter = InflowMeter.new
  end

  def create
    @errors = ''
    @inflow_meter = []
    begin
      if inflow_meter_params[:name].present? && inflow_meter_params[:calibration_unit].present? && inflow_meter_params[:device_EUI].present? && inflow_meter_params[:daily_consent].present?
        @farm_block = FarmBlock.find_by(id: params[:farm_block_id])
        @inflow_meter = InflowMeter.new(inflow_meter_params)
        @inflow_meter.farm_block_id = @farm_block.id


        begin
          my_device = {
              "name": inflow_meter_params[:name],
              "description": "New device" ,
              "tags": [
                  {
                      "key": "sigfox_id",
                      "value": "1C8E99"
                  },
                  {
                      "key": "sensor_input",
                      "value": "1"
                  }
              ],
              "attributes": [
                  {
                      "name": "location",
                      "dataType": "gps"
                  },
                  {
                      "name": "snr",
                      "dataType": "number"
                  },
                  {
                      "name": "station",
                      "dataType": "string"
                  },
                  {
                      "name": "data",
                      "dataType": "string"
                  },
                  {
                      "name": "avgSnr",
                      "dataType": "number"
                  },
                  {
                      "name": "rssi",
                      "dataType": "number"
                  },
                  {
                      "name": "seqNumber",
                      "dataType": "number"
                  },
                  {
                      "name": "pulse",
                      "dataType": "number"
                  },
                  {
                      "name": "battery",
                      "dataType": "number"
                  },
                  {
                      "name": "totalflow",
                      "dataType": "number"
                  }
              ],
              "deviceClass": "standalone"
          }
          #   url= "https://590bc7a2c8f13000014788c5.onlosant.com/devices"
          # r=Net::HTTP.post_form(url, my_device)
          urlApi =  "https://59b9ac8ebc9c9b0007659ade.onlosant.com/devices"
          #   urlApi =  "https://590bc7a2c8f13000014788c5.onlosant.com/devices"
          response = HTTP.post(urlApi, :json => my_device)
          # client = LosantRest::Client.new(auth_token: session[:losant_auth_token], url: url)
          # result = client.devices.post(applicationId: ENV['LOSANT_APP_ID'], device: my_device)
          # rescue => e
          #   @error = e.to_s
          #   flash[:failure] = @error
          #   return render :action => 'new'
        end



        if @inflow_meter.save
          #   begin
          #     Sensor.create_thing(@inflow_meter)
          #     Sensor.create_thing_database(@inflow_meter)
          #     Sensor.create_thing_rule(@inflow_meter)
          #   rescue Aws::DynamoDB::Errors::ResourceInUseException => error
          #     @errors = error
          #     return render :action => 'new'
          #   rescue Aws::DynamoDB::Errors::ValidationException => error
          #     @errors = error
          #     return render :action => 'new'
          #   rescue Aws::IoT::Errors::InvalidRequestException => error
          #     @errors = error
          #     return render :action => 'new'
          #   end
          #   return redirect_to inflow_meter_path(@inflow_meter)
          # else
          #   @errors = @inflow_meter.errors.messages

          return redirect_to farm_block_path(@farm_block)
        end
      else
        @errors = "Data not empty"
        flash[:failure] = @errors
        render :action => 'new'
      end
    rescue => e
      @errors = "Error!" + e.to_s
      flash[:failure] = @errors
      render :action => 'new'
    end
  end

  def edit
    @inflow_meter = InflowMeter.find_by(id: params[:id])
  end

  def show
    @inflow_meter = InflowMeter.find_by(id: params[:id])
    @alerts = @inflow_meter.alerts
    gon.inflow_meter = {}

    #================================================#
    # Get state device info = Meter
    #================================================#
    begin
      client = LosantRest::Client.new(auth_token: ENV['LOSANT_API_TOKEN'], url: "https://api.losant.com")
      @result = client.device.get_composite_state( applicationId: ENV['LOSANT_APP_ID'], deviceId: @inflow_meter.device_EUI)
    rescue Exception => e
      @errors = e.to_s
    end
    #================================================#
    # End get state device info = Meter
    #================================================#

    # unless Sensor.table_exists?(@inflow_meter.device_EUI)
    #   begin
    #     Sensor.create_thing_database(@inflow_meter)
    #   rescue Aws::DynamoDB::Errors::ValidationException => error
    #     puts error
    #     message = "There is a problem with your sensor's device EUI!"
    #     @error = {
    #       error: error,
    #       message: message
    #     }
    #   end
    # end

    # begin
    #   resp = Sensor.scan_dynamodb(@inflow_meter)
    # rescue Aws::DynamoDB::Errors::ResourceNotFoundException => error
    #   puts error
    #   message = "Sensor Database Initialising!"
    #   @error = {
    #     message: message,
    #     error:   error
    #   }
    #   gon.inflow_meter[:data] = []
    # rescue Aws::DynamoDB::Errors::ValidationException => error
    #   puts error
    #   message = "There is a problem with your sensor's device EUI!"
    #   @error = {
    #     error: error,
    #     message: message
    #   }
    # else
    #   all_items = resp.items

    #   calculated_data = all_items.map do |entry|
    #     flow_data = FlowMeterData.new(@inflow_meter, entry["payload"]["data"], entry["timestamp"])
    #     flow_data.convert_base64_to_decimal
    #     flow_data.calculate_flow_data
    #     flow_data
    #   end

    #   gon.inflow_meter[:data] = calculated_data
    # end

    gon.inflow_meter[:sensor] = @inflow_meter
  end

  def update
    @inflow_meter = InflowMeter.find_by(id: params[:id])

    if @inflow_meter.update_attributes(inflow_meter_params)
      redirect_to inflow_meter_path(@inflow_meter)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @inflow_meter = InflowMeter.find_by(id: params[:id])
    @inflow_meter.destroy
    redirect_to dashboard_path(current_user)
  end

  private

  def inflow_meter_params
    params.require(:inflow_meter).permit(:name, :calibration_unit, :device_EUI, :daily_consent,:type)
  end
end

app/helpers/inflow_meter_helper.rb
module InflowMeterHelper
end

app/views/inflow_meters/_card.html.erb
<div class="col s12 m12 l4">
  <div class="card large darken-2 sticky-action">
      <div class="card-content">
          <div class="inflowChart" id="inflow-meter<%=locals[:index]%>"></div>

          <span class="card-title activator grey-text text-darken-4"><%=locals[:meter].name%></span>
          <span id="inflow-meter-data" class="card-title activator grey-text text-darken-4" style="align-content: center;"></span><br>          
          Last Reading: <span id="inflow-meter-lastReading<%=locals[:index]%>"></span><br>
          Status: <span id="inflow-meter-status<%=locals[:index]%>"></span>                
      </div>

      <div class="card-reveal grey lighten-3">
        <span class="card-title grey-text text-darken-4">Close<i class="fa fa-times right"></i></span>
      </div>

      <div class="card-action" style="background: lightgrey;">
        <%=link_to "See More", inflow_meter_path(locals[:meter].id)%>
      </div>
  </div>
</div>

app/views/inflow_meters/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-4">
      <%=form_for [@farm_block, @inflow_meter] do |f|%>
        <div class="input-group input-group-lg">
          <%=f.label :name%>
          <%=f.text_field :name, class: "form-control"%>
        </div>

        <div class="input-group input-group-lg">
          <%=f.label :calibration_unit%>
          <%=f.text_field :calibration_unit, class: "form-control"%>
        </div>

        <div class="input-group input-group-lg">
          <%=f.submit "Submit", class: "btn btn-primary"%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/inflow_meters/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-4">
      <%=form_for @inflow_meter, url: farm_block_inflow_meters_path, method: :post do |f|%>
        <div class="input-group input-group-lg">
          <%=f.label :name%>
          <%=f.text_field :name, class: "form-control"%>
        </div>

        <div class="input-group input-group-lg">
          <%=f.label :calibration_unit%>
          <%=f.text_field :calibration_unit, class: "form-control"%>
        </div>

        <div class="input-group input-group-lg">
          <%=f.label :device_EUI%>
          <%=f.text_field :device_EUI, class: "form-control"%>
        </div>

        <div class="input-group input-group-lg">
          <%=f.label :daily_consent%>
          <%=f.text_field :daily_consent, class: "form-control"%>
        </div>

        <div class="form-group" style="text-align:center;color:#ff0000">
          <p><strong><%if flash[:failure]%>
            <%= render 'layouts/login_failure'%>
          <%end%></strong></p>          
        </div>        

        <div class="input-group input-group-lg">
          <%=f.submit "Submit", class: "btn btn-primary"%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/inflow_meters/show.html.erb
<div class="container">
  <div class="row">
      <div class="center-align chartTitle">
        <%=@inflow_meter.name%>
        <%=link_to edit_inflow_meter_path do%>
          <i class="material-icons" style="color: grey;"><span class="editButton">mode_edit</span></i>
        <%end%>
      </div>
  </div>
    
    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @inflow_meter.calibration_unit%>
        <div class="chartDetailsTitle">Calibration unit:</div>
        <div class="chartDetails"><%=@inflow_meter.calibration_unit%></span></div>
        <%else%>
        <div class="chartDetails">No Calibration Unit</div>
        <%end%>
      </div>
    </div>    

<div class="row">
  <div class="col s12 m12 l12 center-align">
  <%if @result['location']%>
    <div class="chartDetailsTitle">Location:</div>
    <div class="chartDetails"><%= @result['location']['value'] %></span></div>
    <%else%>
    <div class="chartDetails">Null</div>
    <%end%>
  </div>
</div>


    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @result['station']%>
        <div class="chartDetailsTitle">Station:</div>
        <div class="chartDetails"><%= @result['station']['value'] %></span></div>
        <%else%>
        <div class="chartDetails">Null</div>
        <%end%>
      </div>
    </div>
    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @result['avgSnr']%>
        <div class="chartDetailsTitle">avgSnr:</div>
        <div class="chartDetails"><%= @result['avgSnr']['value'] %></span></div>
        <%else%>
        <div class="chartDetails">Null</div>
        <%end%>
      </div>
    </div>
    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @result['rssi']%>
        <div class="chartDetailsTitle">rssi:</div>
        <div class="chartDetails"><%= @result['rssi']['value'] %></span></div>
        <%else%>
        <div class="chartDetails">Null</div>
        <%end%>
      </div>
    </div>
    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @result['pulse']%>
        <div class="chartDetailsTitle">Pulse:</div>
        <div class="chartDetails"><%= @result['pulse']['value'] %></span></div>
        <%else%>
        <div class="chartDetails">Null</div>
        <%end%>
      </div>
    </div>
    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @result['battery']%>
        <div class="chartDetailsTitle">Battery:</div>
        <div class="chartDetails"><%= @result['battery']['value'] %></span></div>
        <%else%>
        <div class="chartDetails">Null</div>
        <%end%>
      </div>
    </div>
    <div class="row">      
      <div class="col s12 m12 l12 center-align">
      <%if @result['totalflow']%>
        <div class="chartDetailsTitle">Totalflow:</div>
        <div class="chartDetails"><%= @result['totalflow']['value'] %></span></div>
        <%else%>
        <div class="chartDetails">Null</div>
        <%end%>
      </div>
    </div>
    <br/>    

    <%if @error%>
      <div id="error-message">
        <%= @error[:message] %>
      </div>
    <%end%>

    <!-- Chart -->
    <div class="row">
      <div id="chart"></div>
    </div>

    <br>

    <div class="row">
      Daily Consent
      <div id="bar-chart"></div>
    </div>

    <%=button_to(inflow_meter_path(@inflow_meter), :method => 'delete', :class => "deleteButton") do%><i class="material-icons" style="font-size: 30px; color: red;"><span class="delete-button">delete</span></i><%end%>

    <h3 class="alertsTitle">
      Alerts
    </h3>

    <div class="row">

      <%if @inflow_meter.alerts%>
        <%@inflow_meter.alerts.each do |alert|%>
          <%=render 'alerts/partials/card', locals: {alert: alert}%>
        <%end%>
      <%end%>

    </div>

    <%=link_to new_inflow_meter_alert_path(@inflow_meter) do%>
      <input class="btn btn-default" type="submit" value="Add New Alert">
    <%end%>
</div>