config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "data" => 'farm_blocks#get_iot_shadows'
  post "data" => 'farm_blocks#get_iot_shadows'

  get "water_tanks/:water_tank_id/data" => 'water_tanks#get_tank_data'
  get "about" => 'welcome#about', :as => "about"
  get "new" => 'devices#new', :as => "new"
  post "new" => 'devices#login'

  get "ok" => 'devices#ok', :as => "ok"

  get "pricing" => "welcome#pricing", :as => "pricing"
  get "blog" => "welcome#blog", :as => "blog"
  get "contact" => "welcome#contact", :as => "contact"
  get "landing" => "welcome#landing", :as => "landing"
  get "users/:user_id/farm_blocks" => "farm_blocks#index", :as => "dashboard"

  post "alert/seen" => "alerts#user_check_alert"
  get "get_all_alerts" => "alerts#get_all_alerts"
  get "farm_block_water_tank" => "farm_blocks#show"

  resources :users, only: [:new, :create, :edit, :update, :show], shallow: true  do

    member do
      get :confirm_email
    end

    resources :farm_blocks, shallow: true do
      resources :addresses
      resources :locations

      resources :water_tanks, shallow: true  do
        resources :locations
        resources :alerts
      end

      resources :inflow_meters do
        resources :locations
        resources :alerts
      end
    end
  end

  resources :sessions, only: [:create, :destroy]
  get "login" => 'sessions#new', :as => "login"
  get "users" => 'users#new'
  get "logout" => 'sessions#destroy', :as => "logout"

  resources :charges

end

app/models/address.rb
class Address < ActiveRecord::Base

  belongs_to :farm_block

  validates_presence_of :address_one,
                        :address_two,
                        :state,
                        :city,
                        :post_code
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :water_tank
  belongs_to :inflow_meter
  belongs_to :alertable, polymorphic: true


  def actions
    [
      ["Text", 1],
      ["Email", 2],
      ["Red Pin Alert", 3],
      ["Amber Pin Alert", 4],
      ["Web Notification", 5],
      ["App Notification", 6]
    ]
  end

  def conditions
    [
      ["IS LESS THAN", "lessThan"],
      ["IS GREATER THAN", "greaterThan"],
    ]
  end

end

app/models/device.rb
class Device < ActiveRecord::Base

  # before_create :confirmation_token
  before_create {generate_token(:auth_token)}

  has_secure_password

  has_many :farm_blocks
  has_many :inflow_meters, through: :farm_blocks
  has_many :water_tanks, through: :farm_blocks

  validates_presence_of :name, :description
  validates_uniqueness_of :email

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end #while User.exists?(column => self[column])
  end


end

app/models/farm_block.rb
class FarmBlock < ActiveRecord::Base

  before_save :default_name

  belongs_to :user
  has_one :location, as: :locationable
  has_one :address, as: :addressable
  has_many :water_tanks
  has_many :inflow_meters

  def has_water_tanks?
    if self.water_tanks.empty?
      return false
    else
      return true
    end
  end

  def has_inflow_meters?
    if self.inflow_meters.empty?
      return false
    else
      return true
    end
  end

  private

  def default_name
    if self.name == ""
      self.name = "Farm Block"
    end
  end
end

app/models/inflow.rb
class Inflow < Meter

end

app/models/inflow_meter.rb
class InflowMeter < ActiveRecord::Base
  belongs_to :farm_block
  has_one :location, as: :locationable
  has_many :alerts, as: :alertable

  def alert_attributes
    [
      ["Output", 1]
    ]
  end

  def get_inflow_data
    return rand(30..100)
  end

  validates_presence_of :calibration_unit
end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :farm_block
  belongs_to :water_tank
  belongs_to :inflow_meter
  belongs_to :locationable, polymorphic: true
end

app/models/meter.rb
class Meter < ActiveRecord::Base
  belongs_to :farm_block
  has_many :alerts, as: :alertable
end

app/models/outflow.rb
class Outflow < Meter

end

app/models/user.rb
class User < ActiveRecord::Base

  # before_create :confirmation_token
  before_create {generate_token(:auth_token)}

  has_secure_password

  has_many :farm_blocks
  has_many :inflow_meters, through: :farm_blocks
  has_many :water_tanks, through: :farm_blocks

  validates_presence_of :first_name, :last_name, :email, :password_digest
  validates_uniqueness_of :email

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # def email_activate
  #   self.email_confirmed = true
  #   self.confirm_token = nil
  #   save!(:validate => false)
  # end
  #
  # private
  #
  # def confirmation_token
  #   if self.confirm_token.blank?
  #     self.confirm_token = SecureRandom.urlsafe_base64.to_s
  #   end
  # end
end

app/models/water_tank.rb
class WaterTank < ActiveRecord::Base
  belongs_to :farm_block
  has_one :location, as: :locationable
  has_many :alerts, as: :alertable

  def alert_attributes
    return [
      ["Volume", 1]
    ]
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meter_helper.rb
module MeterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shared/_error.html.erb
<li class="collection-item">
  <i class="material-icons">warning</i>
  <div style="vertical-align: middle; display: inline-flex;">
    <%=locals[:error][0]%> <%=locals[:error][1][0]%>
  </div>
</li>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <%if logged_in?%>
      <%= render 'shared/footer/logged_in_footer'%>
    <%else%>
      <%= render 'shared/footer/logged_out_footer'%>
    <%end%>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="top-nav" style="">
    <span class="nav-wrapper">
      <%if logged_in?%>
        <%= render 'shared/navbar/logged_in_nav'%>
      <%else%>
        <%= render 'shared/navbar/logged_out_nav'%>
      <%end%>
    </span>
</nav>


<script type="text/javascript">
    $(".button-collapse").sideNav({
      closeOnClick: true
    });
</script>

app/views/shared/_sidebar.html.erb
<ul class="side-nav" id="slide-out" style="background: #F2F2F2;">
    <li class="logo">
      <%=link_to root_path do%>
        <div class="side-title"><span style="color: white;">Knode</span><span style="color: #ECBE13;">.</span></div>
      <%end%>
    </li>
    <li class="bold">
      <strong>
        <div class="side-nav-farm">
          <%if logged_in?%>
            <%=link_to "Dashboard", dashboard_path(current_user)%>
          <%end%>
        </div>
      </strong>
    </li>

    <%if logged_in?%>
    <%current_user.farm_blocks.each do |fb|%>
    <strong>
      <div class="side-nav-farm">
        <li><%=link_to fb.name, farm_block_path(fb)%></li>
      </div>
    </strong>
    <div class="navSubTitle">Water Tanks</div>
    <li><div class="divider"></div></li>
    <div class="side-nav-farm">
      <%fb.water_tanks.each do |wt|%>
        <li><%=link_to wt.name, water_tank_path(wt), {class: "subheader"}%></li>
      <%end%>
    </div>
    <div class="navSubTitle">Inflow Meters</div>
    <li><div class="divider"></div></li>
    <div class="side-nav-farm">
      <%fb.inflow_meters.each do |inflmt|%>
        <li><%=link_to inflmt.name, inflow_meter_path(inflmt), {class: "subheader"}%></li>
      <%end%>
    </div>
    <%end%>

    <%end%>
</ul>

app/views/shared/navbar/_logged_in_bread.html.erb
<ul class="" style="">
  <li style="padding-left: 20px; width: 100%; background: #545959;">
    <%= link_to "Dashboard", user_farm_blocks_path(current_user), class:"breadcrumb"%>
    <%= link_to Rails.application.config.current_farm_block_name, user_farm_blocks_path(current_user), class:"breadcrumb"%>
  </li>
</ul>

app/views/shared/navbar/_logged_in_nav.html.erb
<ul class="nav left">
  <li style="padding-left: 0px;">
    <a data-activates="slide-out" class="show-on-large button-collapse">
      <i class="large material-icons">view_module</i>
    </a>
  </li>
</ul>

<ul class="nav center">
  <li class="nav-logo">
    <!-- <%#if current_page?("controller"=>"farm_blocks", "action"=>"index", "user_id"=> current_user.id)%> -->
      Knode<span style="color: orange;">.</span></a>
    <!-- <%#elsif current_page?("controller"=>"farm_blocks", "action"=>"show")%>
      <%#currentFarmBlock = @farm_block.name%>
      <span style="">
        <li>
          <%#= currentFarmBlock%>
          <%#=link_to edit_farm_block_path(current_user) do%>
              <span class="material-icons" style="font-size: 1.5em; color: white;">mode_edit</span>
          <%#end%>
        </li>
      </span>
    <%#else%>
      <span style="">
        <li>
          <%#= currentFarmBlock%>
          <%#=link_to edit_farm_block_path(current_user) do%>
              <span class="material-icons" style="font-size: 1.5em; color: white;">mode_edit</span>
          <%#end%>
        </li>
      </span>
    <%#end%> -->
  </li>
</ul>

<ul class="nav-mobile nav right" id="nav-mobile">
  <li><a class="dropdown-button" href="#!" data-activates="dropdown2" data-beloworigin="true"><span class="noficicationImage" id="notif"><%=image_tag("notificationBadge.png", class:"notification")%></span></i></a></li>
  <li><%=link_to "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}", user_path(current_user)%></li>
  <li><%=link_to "Logout", logout_path%></li>
</ul>

<ul id="dropdown2" class="dropdown-content">
  <div class="alertTitle"><strong>Alerts</strong></div>
  <div class="alertContent" id="noAlerts"></div>
  <div id="alertList">
    <%get_device_count.each_with_index do |alert, i|%>
      <div id="alert<%=i%>">
        <li>
          <div class="alertContent" id="alertDiv" style="word-wrap: break-word;">
            <div class="alertClose"><input class="alertBtnClose" type="button" value="x" id="b<%=i%>" onclick="delete<%=i%>();checkNotif()"/></div>
            <strong><%=alert[:name]%></strong>
            <br>
          </div>
          Volume <%=alert[:type]%> <%=alert[:data]%>
        </li>
      </div>
      <script>
        function delete<%=i%>() {
            var b<%=i%> = document.getElementById('b<%=i%>');

            if(b<%=i%>.onclick="delete<%=i%>();") {
              document.getElementById('alert<%=i%>').innerHTML = "";
              checkNotif();
            }
        }
      </script>
    <%end%>
  </div>
</ul>

<script type="text/javascript">
  $.ajax({
    url:"/get_all_alerts",
  }, function (data) {

    debugger
  })
</script>

<script type="text/javascript">
  function checkNotif() {
    if(document.getElementById('alertList').innerHTML.indexOf("alertContent") != -1) {
      document.getElementById('notif').innerHTML = '<%=image_tag("notificationBadge.png", class:"notification")%>';
    }
    else {
      document.getElementById('notif').innerHTML = '<%=image_tag("notification.png", class:"notification")%>';
      document.getElementById('noAlerts').innerHTML = '<li><strong><center><p>No Alerts</p></center></strong></li>';
    }
  }
  function changeText() {
      var b1 = document.getElementById('b1');

      if(b1.onclick="changeText();") {
        document.getElementById('alert0').innerHTML = "";
        checkNotif();
      }
  }
  checkNotif();
</script>

app/views/shared/navbar/_logged_out_nav.html.erb
<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">view_module</i></a>
<div class="navbar-content" style="background: #414747;">
  <%= link_to root_path do %>
    <ul class="nav-title nav left" style="">
      Knode<span style="color: orange;">.</span>
    </ul>
  <%end%>
  <ul class="nav center hide-on-med-and-down">
    <li><%=link_to "Home", root_path%></li>
    <li><%=link_to "About", about_path%></li>
    <li><%=link_to "Contact", contact_path%></li>
    <li><%=link_to "Pricing", pricing_path%></li>
    <li><%=link_to "Blog", blog_path%></li>
  </ul>
  <ul class="nav right hide-on-med-and-down">
    <li><%=link_to "Sign up", new_user_path%></li>
    <li><%=link_to "Login", login_path%></li>
  </ul>
  <ul class="side-nav" id="mobile-demo" style="background: #F2F2F2;">
    <li class="logo">
      <%=link_to root_path do%>
        <span class="side-title" style="color: white;">Knode</span><span class="side-title" style="color: orange;">.</span>
      <%end%>
    </li>
    <span class="side-nav-farm" style="color: orange;">
      <li><%=link_to "Home", root_path%></li>
      <li><%=link_to "About", about_path%></li>
      <li><%=link_to "Contact", contact_path%></li>
      <li><%=link_to "Pricing", pricing_path%></li>
      <li><%=link_to "Blog", blog_path%></li>
      <br>
      <li><%=link_to "Sign up", new_user_path%></li>
      <li><%=link_to "Login", login_path%></li>
    </span>
  </ul>
</div>