config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "data" => 'farm_blocks#get_iot_shadows'
  post "data" => 'farm_blocks#get_iot_shadows'

  get "water_tanks/:water_tank_id/data" => 'water_tanks#get_tank_data'
  get "about" => 'welcome#about', :as => "about"
  get "new" => 'devices#new', :as => "new"
  post "new" => 'devices#login'

  get "ok" => 'devices#ok', :as => "ok"

  get "pricing" => "welcome#pricing", :as => "pricing"
  get "blog" => "welcome#blog", :as => "blog"
  get "contact" => "welcome#contact", :as => "contact"
  get "landing" => "welcome#landing", :as => "landing"
  get "users/:user_id/farm_blocks" => "farm_blocks#index", :as => "dashboard"

  post "alert/seen" => "alerts#user_check_alert"
  get "get_all_alerts" => "alerts#get_all_alerts"
  get "farm_block_water_tank" => "farm_blocks#show"

  resources :users, only: [:new, :create, :edit, :update, :show], shallow: true  do

    member do
      get :confirm_email
    end

    resources :farm_blocks, shallow: true do
      resources :addresses
      resources :locations

      resources :water_tanks, shallow: true  do
        resources :locations
        resources :alerts
      end

      resources :inflow_meters do
        resources :locations
        resources :alerts
      end
    end
  end

  resources :sessions, only: [:create, :destroy]
  get "login" => 'sessions#new', :as => "login"
  get "users" => 'users#new'
  get "logout" => 'sessions#destroy', :as => "logout"

  resources :charges

end

app/models/address.rb
class Address < ActiveRecord::Base

  belongs_to :farm_block

  validates_presence_of :address_one,
                        :address_two,
                        :state,
                        :city,
                        :post_code
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :water_tank
  belongs_to :inflow_meter
  belongs_to :alertable, polymorphic: true


  def actions
    [
      ["Text", 1],
      ["Email", 2],
      ["Red Pin Alert", 3],
      ["Amber Pin Alert", 4],
      ["Web Notification", 5],
      ["App Notification", 6]
    ]
  end

  def conditions
    [
      ["IS LESS THAN", "lessThan"],
      ["IS GREATER THAN", "greaterThan"],
    ]
  end

end

app/models/device.rb
class Device < ActiveRecord::Base

  # before_create :confirmation_token
  before_create {generate_token(:auth_token)}

  has_secure_password

  has_many :farm_blocks
  has_many :inflow_meters, through: :farm_blocks
  has_many :water_tanks, through: :farm_blocks

  validates_presence_of :name, :description
  validates_uniqueness_of :email

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end #while User.exists?(column => self[column])
  end


end

app/models/farm_block.rb
class FarmBlock < ActiveRecord::Base

  before_save :default_name

  belongs_to :user
  has_one :location, as: :locationable
  has_one :address, as: :addressable
  has_many :water_tanks
  has_many :inflow_meters

  def has_water_tanks?
    if self.water_tanks.empty?
      return false
    else
      return true
    end
  end

  def has_inflow_meters?
    if self.inflow_meters.empty?
      return false
    else
      return true
    end
  end

  private

  def default_name
    if self.name == ""
      self.name = "Farm Block"
    end
  end
end

app/models/inflow.rb
class Inflow < Meter

end

app/models/inflow_meter.rb
class InflowMeter < ActiveRecord::Base
  belongs_to :farm_block
  has_one :location, as: :locationable
  has_many :alerts, as: :alertable

  def alert_attributes
    [
      ["Output", 1]
    ]
  end

  def get_inflow_data
    return rand(30..100)
  end

  validates_presence_of :calibration_unit
end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :farm_block
  belongs_to :water_tank
  belongs_to :inflow_meter
  belongs_to :locationable, polymorphic: true
end

app/models/meter.rb
class Meter < ActiveRecord::Base
  belongs_to :farm_block
  has_many :alerts, as: :alertable
end

app/models/outflow.rb
class Outflow < Meter

end

app/models/user.rb
class User < ActiveRecord::Base

  # before_create :confirmation_token
  before_create {generate_token(:auth_token)}

  has_secure_password

  has_many :farm_blocks
  has_many :inflow_meters, through: :farm_blocks
  has_many :water_tanks, through: :farm_blocks

  validates_presence_of :first_name, :last_name, :email, :password_digest
  validates_uniqueness_of :email

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # def email_activate
  #   self.email_confirmed = true
  #   self.confirm_token = nil
  #   save!(:validate => false)
  # end
  #
  # private
  #
  # def confirmation_token
  #   if self.confirm_token.blank?
  #     self.confirm_token = SecureRandom.urlsafe_base64.to_s
  #   end
  # end
end

app/models/water_tank.rb
class WaterTank < ActiveRecord::Base
  belongs_to :farm_block
  has_one :location, as: :locationable
  has_many :alerts, as: :alertable

  def alert_attributes
    return [
      ["Volume", 1]
    ]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    unless logged_in?
      redirect_to landing_path
    end
  end

  def landing

  end

  def about

  end

  def pricing

  end

  def blog
    file = File.read('app/views/welcome/blog_content.json')
    @content = JSON.parse(file)
    @images = ['farmer.jpg', 'mountain.JPG', 'irrigation.jpg']
  end

  def contact

  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/farm_block_helper.rb
module FarmBlockHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meter_helper.rb
module MeterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_blog_post.html.erb
<!-- Blog Post START -->
<div class="col s12 m10 offset-m1 l8 offset-l2">

  <ul class="blog-post">

    <!-- IMAGE -->
        <li class="image-container">
          <%= image_tag "#{locals[:image]}", class:"circle"%>
        </li>
    <!-- IMAGE END -->

    <!-- CONTENT START -->
      <li class="content-container">

        <!-- Title of Blog Post -->
        <h5 class="blog-title">
          <a class="blog-title-link" href="#">
            <%=locals[:title]%>
          </a>
        </h5>

        <!-- Main Body of Blog post -->
        <p class="blog-main">
          <%= locals[:content]%>
        </p>

      </li>
    <!-- CONTENT END -->

  </ul>
</div>
<!-- Blog Post END -->

app/views/welcome/about.html.erb
<div class="row">
  <h2 style="text-align:center;">About Us</h2>
</div>

<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">

    <div style="padding:10px; border: 1px solid #9facbd; border-radius: 2px; margin-top:10px; margin-bottom:10px; overflow:hidden; height:200px;">

      <%= image_tag 'water-icons/png/bucket.png', class:"responsive-img", style:"filter: grayscale(80%); max-width:300px; max-height: 170px; margin-left: 30px;"%>

      <div class="about-us content-wide">

        <h4 style="text-align:center; color:#ff9800">Who We Are</h4>

        <p class="paragraph">
          Farmers by trade, we know and have experienced first-hand the horrors of losing large and vast quantities of water through unfortunate and costly leakages.
        </p>

      </div>

    </div>

  </div>
</div>


<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">

    <div style="padding:10px; border: 1px solid #9facbd; border-radius: 2px; overflow:auto; margin-top:10px; margin-bottom:10px; height:200px;">

      <div class="about-us content-wide">

        <h4 style="text-align:center; color:#ff9800">What We Do</h4>

        <p class="paragraph">
          Currently there is no way to effiently check and manage water supplies across large heactares of property other than to manually drive out to location and investigate your water tanks directly.
          <!-- If you suspect water may be gushing from your tank, you have no objective way to check.  -->
          Our platform hopes to give clarity to farmers so they can act quickly and effectively.
        </p>

      </div>

      <%= image_tag 'water-icons/png/water-4.png', class:"responsive-img", style:"filter: grayscale(80%); diplay:inline-block; float:right; max-width:300px; max-height: 170px; margin-right: 30px;"%>
    </div>

  </div>
</div>

<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">

    <div style="padding:10px; border: 1px solid #9facbd; border-radius: 2px; margin-top:10px; overflow:auto; height:200px;">

      <%= image_tag 'water-icons/png/piggy-bank.png', class:"responsive-img", style:"filter: grayscale(80%); max-width:300px; max-height: 170px; margin-left:30px;"%>

      <div class="about-us content-wide">

        <h4 style="text-align:center; color: #ff9800">Our Aim</h4>

        <p class="paragraph" >
          Here at Knode Ltd. we have set out to revolutionise the way farmers oversee their water supplies. Implementing emerging IoT technologies and utilising the pure power and speed of the cloud, we ernestly believe we have built and refined a fault-tolerant platform that will benefit those that use it.
        </p>

      </div>

    </div>

  </div>
</div>

<br><br><br>

<style media="screen">

  .about-us {

  }

  .content-wide {
    margin-left: 20px;
    display:inline-block;
    position:absolute;
    width:40%;
  }

  .content-mobile {
    width: 80%;
    margin-left: auto;
    margin-right: auto;
  }

</style>

<script type="text/javascript">
  var $window = $(window);

   $window.resize(function() {
     var aboutUs = $(".about-us");

     if ($window.width() < 850) {
       var images = $(".responsive-img");

       $(".paragraph").css("font-size", "");
       $(".paragraph").css("font-size", "1em");

       for (var i = 0; i < images.length; i++) {
         $(images[i]).css("display","none");
         $(aboutUs[i]).removeClass("content-wide");
         $(aboutUs[i]).addClass("content-mobile");
       }
    }

    if ($window.width() > 850) {
      var images = $(".responsive-img");

      $(".paragraph").css("font-size", "");
      $(".paragraph").css("font-size", "0.9em");

      for (var i = 0; i < images.length; i++) {
        $(images[i]).css("display", "");
        $(images[i]).css("display", "absolute");

        if ($(aboutUs[i]).hasClass("content-mobile")) {
          $(aboutUs[i]).removeClass("content-mobile");
        }
        $(aboutUs[i]).addClass("content-wide");
      }
   }
  })
</script>

app/views/welcome/blog.html.erb
<div class="row">
  <h2 style="text-align:center">Blog</h2>
</div>

<div class="row">

  <%@content.each_with_index do |blog_post, index|%>
  <%= render 'welcome/blog_post', locals: {title: "#{blog_post["title"]}", content: "#{blog_post["content"]}", image: "#{@images[index]}"}%>
  <%end%>
</div>

<!-- Place in scss file -->
<style media="screen">

  .blog-post {
    height: 150px;
    min-width: 700px;
    border: 1px solid black;
    list-style-type: none;
    padding: 0;
  }

  .blog-post li {
    float: left;
  }

  .image-container {
    margin-left: 10px;
    margin-top: 15px;
  }

  .image-container img {
    height: 120px;
    width: 150px;
    display: block;
  }

  .content-container {
    position: relative;
    height: 100%;
    width: 75%;
    display: block;
  }

  .blog-title {
    position: absolute;
    padding-left: 20px;
    z-index: 1;
  }

  .blog-title a {
    display: block;
  }

  .blog-main {
    position: absolute;
    padding-top: 55px;
    padding-left: 20px;
    height: 100%;
    width:100%;
    word-wrap: break-word;
    display: inline-block;
    margin-bottom: 0;
    margin-top: 0;

    /* Buggy */
    overflow:hidden;
    text-overflow: ellipsis;
    /* ^^^ */
  }

</style>

app/views/welcome/contact.html.erb
<div class="row" style="text-align:center;">
  <h2>Contact Us</h2>
</div>

<div class="row">

  <div class="col s12 m6 offset-m3">

    <p class="flow-text">
      Have an urgent question? Feel free to drop us a line, we'd be more than happy to help you out.
    </p>

  </div>

</div>

<div class="row">
    <div class="col s6 m3 l2 offset-l2">
      <div class="card">
        <div class="card-content">

          <div class="photo">
            <%=image_tag "Richard.jpg", class: "circle responsive-img", style: "max-height:250px; margin-left:auto;margin-right:auto;display:block;"%>
          </div>

          <div class="card-title" style="text-align:center; font-size: 1.5rem;"><span class="flow-text">Richard Wildman</span></div>
          <div class="card-title" style="text-align:center; font-size: 1rem;">CTO</div>


            <div class="card-action">
              <a href="mailto:richard@knode.co.nz" style="float:left; font-size: 1rem;">Email</a>
              <a href="#" style="float:right; font-size: 1rem;">+64 0211587239</a>
            </div>

        </div>
      </div>
    </div>

    <div class="col s6 m3 l2">
      <div class="card">
        <div class="card-content">

          <div class="photo">
            <%=image_tag "Scott.jpg", class: "circle responsive-img", style: "max-height:250px; margin-left:auto;margin-right:auto;display:block;"%>
          </div>

          <div class="card-title" style="text-align:center; font-size: 1.5rem;">Scott Townshend</div>
          <div class="card-title" style="text-align:center; font-size: 1rem;">CEO</div>


            <div class="card-action">
              <a href="mailto:scott@knode.co.nz" style="float:left; font-size: 1rem;">Email</a>
              <a href="#" style="float:right; font-size: 1rem;">+64 0210566770</a>
            </div>

        </div>
      </div>
    </div>

    <div class="col s6 m3 l2">
      <div class="card">
        <div class="card-content">

          <div class="photo">
            <%=image_tag "Marcus.jpg", class: "circle responsive-img", style: "max-height:250px; margin-left:auto;margin-right:auto;display:block;"%>
          </div>

          <div class="card-title" style="text-align:center; font-size: 1.5rem;">Marcus Graham</div>
          <div class="card-title" style="text-align:center; font-size: 1rem;">COO</div>


            <div class="card-action">
              <a href="mailto:marcus@knode.co.nz" style="float:left; font-size: 1rem;">Email</a>
              <a href="#" style="float:right; font-size: 1rem;">+64 021657585</a>
            </div>

        </div>
      </div>
    </div>

    <div class="col s6 m3 l2">
      <div class="card">
        <div class="card-content">

          <div class="photo">
            <%=image_tag "Mike.jpg", class: "circle responsive-img", style: "max-height:250px; margin-left:auto;margin-right:auto;display:block;"%>
          </div>

          <div class="card-title" style="text-align:center; font-size: 1.5rem;">Mike Jenkins</div>
          <div class="card-title" style="text-align:center; font-size: 1rem;">Corporate Affairs</div>


            <div class="card-action">
              <a href="mailto:mike@knode.co.nz" style="float:left; font-size: 1rem;">Email</a>
              <a href="#" style="float:right; font-size: 1rem;">+64 0212265128</a>
            </div>

        </div>
      </div>
    </div>
</div>

<div class="row">

</div>


<!--

 - Modal Contact card?

 -->

app/views/welcome/index.html.erb
<div class="parallax-container" style="width: 100%;">
    <div class="parallax">
      <%=image_tag("farmland.jpg")%>
    </div>
  <br>
  <br>
  <div class="header1 center" style="color: #F2F2F2;">Knode<span style="color: orange;">.</span></div>
  <div class="container">

    <div class="row center">
      <div class="header2 col s12 m12" style="color:#F2F2F2;">

        Automated Water Metric Solutions
      </div>
    </div>

    <!--<div class="row center">
      <%=link_to root_path do %>
      <div class="btn btn-primary btn-lg" role="button">Learn more &raquo;</div>
      <%end%>
    </div>-->
  </div>
</div>



<div style="width: 100%;padding-top: 7rem; padding-bottom: 5rem;  background-color: white;">
       <div class="container">
         <div class="row">
           <div class="col l6 s12"><img src="assets/devices.png" style="max-width: 100%;"></div>
           <div class="col l6 s12">
             <h4 style="text-align: right; color: black;  display: inline-block; vertical-align: middle; line-height: normal;">Manage and Monitor all your water assets across your farm by utilising our state-of-the-art hardware, networking and application bundled service.</h4>
           </div>
         </div>
       </div>
     </div>

<div id="aboutus" style="width: 100%; background-color: #s;">
       <div class="container" style="height: 100%; padding-top: 5rem; padding-bottom: 5rem;">
           <img src="assets/chart.png" style="width: 100%;">
           <br>
           <img src="assets/chart (1).png" style="width: 100%;">

           <div class="row">
             <div class="col s12 m12">
               <center><p>Have an urgent question? Feel free to email us, we'd be more than happy to help you out.</p>
               <a class="waves-effect waves-light btn modal-trigger orange" href="mailto:info@knode.co.nz" style="z-index: 0 !important;">Email Us</a></center>
             </div>
           </div>
       </div>
     </div>

<div class="container">
  <div class="row">
    <div class="section">

      <div class="col s12 m12">
        <div class="icon-block">
          <!-- <div class=""></div>  ICON-->
          <div class="subheader-index center accent-2"style="color: orange;">What We Offer</div> <!-- HEADER -->
            <p class="condensed-light">
              Manage, Monitor and Alert on the water assets across your farm utilising our state-of-the-art hardware, networking and application bundled service. Our advanced sensor technology measure water tank levels and water flow in real-time on any device. Most importantly Knode is affordable and fast to deploy whether you're a hobby or corporate farmer.
            </p>
          </div>
        </div>
        <div class="divider"></div>


        <div class="col s12 m6">
          <div class="icon-block" style="margin-bottom: 20px;">
            <!-- <div class=""></div>  ICON-->
            <div class="subheader-index center accent-2"style="color: orange;">Round The Clock Analysis</div> <!-- HEADER -->
              <p class="condensed-light">
                Knode is built on the latest proven Internet of Things technology for an always on, reliable and secure experience. We have integrated the fastest cloud technologies for optimal user experience. Best of all, Knode is available on mobile, in the palm of your hand - anytime, anywhere on any device.
              </p>
            </div>
          </div>

          <div class="col s12 m6">
            <div class="icon-block" style="margin-bottom: 20px;">
              <!-- <div class=""></div>  ICON-->
              <div class="subheader-index center accent-2" style="color: orange;">Never Miss a Moment</div> <!-- HEADER -->
                <p class="condensed-light">
                 Knode provides you with a view of your critical water metrics and refreshes every minute of every day. Knode has actionable measures in place that provide meaningful alerts and feedback on your water supplies, prompting action when leakages, spills, blockages or even dry spells occur.
                </p>
              </div>
            </div>
            <div class="col s12 m12">
              <button type="button" class="btn" style="background-color:#ff9800; margin-left:auto; margin-right:auto; display:block;">
                <a href="/about" style="color:white;">Read More</a>
              </button>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    // Get the modal
    var modal = document.getElementById('myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
          modal.style.display = "none";
      }
    }

    modal.style.display = "block";
  </script>

app/views/welcome/landing.html.erb
<div class="landingBackground">
    <div class="parallax">
      <%=image_tag('vines.jpg')%>
    </div>
  <br>
  <br>
  <div class="header1 center" style="color: #F2F2F2; position: relative; top: 7.50%;">Knode<span style="color: orange;">.</span></div>
</div>

<div class="container">
  <div class="row">
    <div class="section">
      <div class="col s12 m12">
        <div class="landingForm">
        <%=form_tag sessions_path, class: "form" do %>
          <fieldset>

            <div class="form-group">
              <label for="email">EMAIL</label>
              <%= email_field_tag 'email', nil, class: 'form-control'%>
            </div>

            <div class="form-group">
              <label for="password">PASSWORD</label>
              <%=password_field_tag 'password', nil, class: "form-control"%>
            </div>

            <div class="form-group">
              <%= check_box_tag :remember_me%>
              <%= label_tag :remember_me%>
            </div>

            <div class="form-group" style="text-align:center;color:#ff0000">
              <p><strong><%if flash[:failure]%>
                <%= render 'layouts/login_failure'%>
              <%end%></strong></p>
            </div>

            <div class="row center">
              <%= submit_tag "Login", class: "btn btn-lg btn-primary btn-bloc"%>
            </div> 


            <div class="form-group">
              <h6>Have not account? Click here to <%= link_to("SignUp", new_user_path) %></h6>
            </div>
          </fieldset>
        <%end%>

      </div>
      </div>
    </div>
  </div>
</div>

<script>
  // Get the modal
  var modal = document.getElementById('myModal');

  // Get the button that opens the modal
  var btn = document.getElementById("myBtn");

  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("close")[0];

  // When the user clicks on <span> (x), close the modal
  span.onclick = function() {
    modal.style.display = "none";
  }

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
  }

  modal.style.display = "block";
</script>

app/views/welcome/pricing.html.erb
<div class="parallax-container">

  <h2 class="header center">Pricing</h2>

<div class="row">

  <div class="col s8 offset-s2 m6 l5 offset-l1">

    <div class="card medium">

      <div class="card-content" style="max-height:100%; text-align:center; margin-bottom:10px;">

        <h4 class="card-title knode-header">Single Farm</h4>

        <p>
          Features of this package include:
        </p>

        <ul>
          <li style="font-style:italic;">Real Time to the minute Water Management for a single farm</li>
          <li style="font-style:italic;">Up to 10 cloud managed water sensors across your farm</li>
          <li style="font-style:italic;">24 hour a day data access on any device</li>
          <li style="font-style:italic;">Alerts and Reporting on leaks and low pressure readings</li>
        </ul>

        <br>

        <p>Monthly Subscription Cost:</p>

        <p>
          <b style="font-size:2em;">
          NZD $199 + GST
          </b>
        </p>

      </div>

      <div class="card-action">

        <button type="button" class="btn waves-effect waves-light" style="margin-left:auto; margin-right: auto; display: block; background-color: #ff9800">
          <a href="mailto:contact@knode.co.nz" style="color:white; margin-left:auto; margin-right:auto">
            Request Quote
          </a>
        </button>

      </div>


    </div>

</div>

  <div class="col s8 offset-s2 m6 l5">

    <div class="card medium" style="position:relative;">

      <div class="card-content" style="max-height:100%; text-align:center;">

        <h4 class="card-title knode-header">Multi Farm</h4>

        <p>
          Features of this package include:
        </p>

        <ul>
          <li style="font-style:italic;">Real Time to the minute Water Management for multiple farms</li>
          <li style="font-style:italic;">Up to <b>100</b> cloud managed water sensors across your farm</li>
          <li style="font-style:italic;">24 hour a day data access on any device</li>
          <li style="font-style:italic;"><b>Alerts</b> and Reporting on leaks and low pressure readings</li>
        </ul>

        <br>

        <p>Monthly Subscription Cost:</p>

        <p>
          <b style="font-size:2em; margin-bottom:5px;">
          NZD $999 + GST
          </b>
        </p>

      </div>

      <div class="card-action">

        <button type="button" class="btn waves-effect waves-light" style="display:block; margin-left:auto; margin-right:auto; background-color: #ff9800">
          <a href="mailto:contact@knode.co.nz" style="color: white; margin-left:auto; margin-right:auto">
            Request Quote
          </a>
        </button>

      </div>
    </div>

  </div>

</div>

<br><br>
<div id="first-image" class="parallax">
  <%= image_tag "MFL.JPG", style: "filter: grayscale(100%);opacity: 0.60; filter: alpha(opacity=60);" %>
</div>

</div>

<br>

<div class="divider"></div>

<div class="row">
  <div class="col s12 m6 offset-m3 l6 offset-l3" style="text-align:center;">
    <h4>Interested in purchasing a subscription?</h4>
    <p class="flow-text">
      Reach out to one of the Knode team members and we will get back to you with a custom-tailored quote based on your needs and requirements.<br>
      <%=link_to "Contact Us", contact_path%>
    </p>
  </div>
</div>

<style media="screen">

  .knode-header {
    color: #ff9800;
    text-decoration: underline;
  }

  .parallax-container {
    height: 100%;
  }
</style>