config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "data" => 'farm_blocks#get_iot_shadows'
  post "data" => 'farm_blocks#get_iot_shadows'

  get "water_tanks/:water_tank_id/data" => 'water_tanks#get_tank_data'
  get "about" => 'welcome#about', :as => "about"
  get "new" => 'devices#new', :as => "new"
  post "new" => 'devices#login'

  get "ok" => 'devices#ok', :as => "ok"

  get "pricing" => "welcome#pricing", :as => "pricing"
  get "blog" => "welcome#blog", :as => "blog"
  get "contact" => "welcome#contact", :as => "contact"
  get "landing" => "welcome#landing", :as => "landing"
  get "users/:user_id/farm_blocks" => "farm_blocks#index", :as => "dashboard"

  post "alert/seen" => "alerts#user_check_alert"
  get "get_all_alerts" => "alerts#get_all_alerts"
  get "farm_block_water_tank" => "farm_blocks#show"

  resources :users, only: [:new, :create, :edit, :update, :show], shallow: true  do

    member do
      get :confirm_email
    end

    resources :farm_blocks, shallow: true do
      resources :addresses
      resources :locations

      resources :water_tanks, shallow: true  do
        resources :locations
        resources :alerts
      end

      resources :inflow_meters do
        resources :locations
        resources :alerts
      end
    end
  end

  resources :sessions, only: [:create, :destroy]
  get "login" => 'sessions#new', :as => "login"
  get "users" => 'users#new'
  get "logout" => 'sessions#destroy', :as => "logout"

  resources :charges

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :water_tank
  belongs_to :inflow_meter
  belongs_to :alertable, polymorphic: true


  def actions
    [
      ["Text", 1],
      ["Email", 2],
      ["Red Pin Alert", 3],
      ["Amber Pin Alert", 4],
      ["Web Notification", 5],
      ["App Notification", 6]
    ]
  end

  def conditions
    [
      ["IS LESS THAN", "lessThan"],
      ["IS GREATER THAN", "greaterThan"],
    ]
  end

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  include AlertValue

  # before_filter :load_alertable

  def index
    @alerts = load_alertable.alerts
  end

  def new
    @alert = load_alertable.alerts.new
  end

  def create
    @alert = load_alertable.alerts.new(alert_params)
    # if (an attribute value of a node)
    #(condition here) of a custom value,
    # then do action

    if @alert.save
      type = alert_params[:condition]
      value = alert_params[:value]
      device_EUI = @alertable.device_EUI

      case type

        when 'greaterThan'
          attach_lambda_to_thing_rule(@alertable.device_EUI, 'greater_than')
        when 'lessThan'
          attach_lambda_to_thing_rule(@alertable.device_EUI, 'less_than')
      end

      create_alert_value(device_EUI, type, value)
      redirect_to context_path(@alert), notice: "Alert Created!"
    else
      @errors = @alert.errors.messages
      render :action => 'new'
    end

  end

  def edit
    @alert = load_alertable
  end

  def show
    @alert = load_alertable
  end

  def update
    @alert = Alert.find_by(id: params[:id])
    if @alert.update_attributes(alert_params)

      redirect_to context_path(@alert), notice: "Alert Updated!"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @alert = load_alertable
    @alert.destroy
    sensor = @alertable.alertable
    remove_lambda_from_thing_rule(sensor.device_EUI)
    redirect_to context_path(@alertable)
  end

  def user_check_alert
    device_EUI = params[:device_EUI]
    data       = params[:data]
    response = confirm_alert_seen(data, device_EUI)
    render :json => response
  end

  def get_all_alerts

    # if a user is NOT logged in
    # return without executing the rest of the method
    return nil unless current_user

    # create a container for the alerts
    # of all sensors / device EUIs
    alerts = []

    # iterate through all the inflow_meters that belong to the logged in user
    current_user.inflow_meters.each do |meter|
      # create a hash (JS Object) to store table name of the alerts
      # that belong to a sensor
      sensor = {table_name: meter.device_EUI}

      # retrieve all alerts for a single sensor.
      # store list of alerts from the API call to AWS in a compartment (key/value pair)
      # of the previously created sensor hash
      sensor[:alerts] = AWSAlert.get_sensor_alerts(meter)

      # Store this hash in all sensor alerts container
      alerts.push(sensor)
    end

    # iterate through all the water tanks that belong to the logged in user
    # essentially the same code as above
    current_user.water_tanks.each do |meter|
      sensor = {table_name: meter.device_EUI}
      sensor[:alerts] = AWSAlert.get_sensor_alerts(meter)

      # Store this hash in all sensor alerts container
      alerts.push(sensor)
    end

    # remove nils from array
    alerts = alerts.select do |a|
      !a[:alerts].nil?
    end

    # access container of alerts for each sensor
    alerts = alerts.each do |a|
      a[:alerts] = a[:alerts].items
    end

    # send back, to the user, the container of alerts in JSON format
    render :json => alerts
  end

  private

  def alert_params
    params.require(:alert).permit(:condition, :value, :action, :node_attribute)
  end

  def load_alertable
    resource, id = request.path.split('/')[1,2]
    unless params["action"] == "user_check_alert"
      @alertable = resource.singularize.classify.constantize.find(id)
    end
  end

  def context_path(context)
    if context.alertable_type == "WaterTank"
      water_tank_path(context.alertable_id)
    elsif context.alertable_type == "OutFlow"
      meter_path(context.alertable_id)
    elsif context.alertable_type == "InflowMeter"
      inflow_meter_path(context.alertable_id)
    elsif context.alertable_type == "Meter"
      meter_path(context.alertable_id)
    else #Incase of error
      dashboard_path
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_index.html.erb
<ul class="col-md-8">
  <%@alerts.each do |alert|%>
  <li><h5>Condition: <%=alert.condition%></h5></li>
  <li>Value: <%=alert.value%></li>
  <li>
    <%=link_to edit_polymorphic_path(alert) do%>
    Edit This Alert
    <%end%>
  </li>
  <li>
    <%=button_to('Delete', alert_path(alert), class:"btn btn-default", :method => 'delete')%>
  </li>
  <%end%>
</ul>

app/views/alerts/edit.html.erb
<%=form_for [@alert] do |f|%>

<div class="form-group">
  <%=f.label :condition, class: "col-sm-2 control-label"%>
  <div class="col-sm-10">
    <%=f.text_field :condition, class: "form-control"%>
  </div>
</div>

<div class="form-group">
  <%=f.label :value, class: "col-sm-2 control-label"%>
  <div class="col-sm-10">
    <%=f.text_field :value, class:"form-control"%>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
<%=f.submit "Update alert", class: "btn btn-default"%>
  </div>
</div>

<%end%>

app/views/alerts/index.html.erb
<div class="container">
  <div class="row">
    <ul class="col-md-8">
      <%@alerts.each do |alert|%>
      <li><h5>Condition: <%=alert.condition%></h5></li>
      <li>Value: <%=alert.value%></li>
      <li>
        <%=link_to edit_polymorphic_path(alert) do%>
          Edit This Alert
        <%end%>
      </li>
      <li>
        <%=button_to('Delete', alert_path(alert), class:"btn btn-default", :method => 'delete')%>
      </li>
      <%end%>
      <li>
        <%if @alertable.is_a? WaterTank%>
        <%=link_to new_water_tank_alert_path do%>
          Add New Alert
          <%end%>

        <%elsif @alertable.is_a?(Inflow)%>
          <%=link_to new_meter_alert_path do%>
            Add New Alert
            <%end%>

          <%elsif @alertable.is_a?(Outflow)%>
            <%=link_to new_meter_alert_path do%>
              Add New Alert
          <%end%>

        <%end%>
      </li>
    </ul>
  </div>
</div>

app/views/alerts/new.html.erb
<br>
<div class="header2 center"><strong>Add New Alert</strong></div>
<%=form_for [@alertable, @alert], class:"form-horizontal" do |f|%>

    <div class="row">
      <div class="input-field col s10 m10 l8 offset-s1 offset-m1 offset-l2">
        <%=f.label :node_attribute%>
        <%== f.select(:node_attribute) do %>
          <% @alertable.alert_attributes.each do |a| -%>
            <%== content_tag(:option, a[0], value: a.last) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <script>
      if
    </script>

    <div class="row">
      <div id="alertCondition" class="col s10 m10 l8 offset-s1 offset-m1 offset-l2">
        <%=f.label :condition%>
        <%=f.select (:condition) do %>
          <%@alert.conditions.each do |c| -%>
            <%= content_tag(:option, c.first, value: c.last) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div id="alertValue"></div>

    <script>
      condition = document.getElementById('alertCondition');
      if (condition.value == "IS BETWEEN" || condition.value == "IS NOT BETWEEN") {
        document.getElementById('alertValue').innerHTML = '<div class="row"><div class="input-field col s10 m10 l8 offset-s1 offset-m1 offset-l2"><%=f.label :value%><%=f.number_field :value, class: "form-control"%></div></div><div class="row"><div class="input-field col s10 m10 l8 offset-s1 offset-m1 offset-l2"><%=f.label :value%><%=f.number_field :value, class: "form-control"%></div></div>';
      }
      else {
        document.getElementById('alertValue').innerHTML = '<div class="row"><div class="input-field col s10 m10 l8 offset-s1 offset-m1 offset-l2"><%=f.label :value%><%=f.number_field :value, class: "form-control"%></div></div>';
      }
    </script>

    <div class="row">
      <div class="input-field col s10 m10 l8 offset-s1 offset-m1 offset-l2">
        <%=f.label :action%>
        <%= f.select(:action) do %>
          <% @alert.actions.each do |c| -%>
            <%= content_tag(:option, c.first, value: c.last) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <br>

    <div class="row center">
      <%=f.submit "Add alert", class: "btn btn-default"%>
    </div>
<%end%>

app/views/alerts/show.html.erb
<%=@alert.condition%>
<%=@alert.value%>